version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_ADDR=auth-service:50051  
      - PRODUCT_SERVICE_ADDR=product-service:50052
      - CART_SERVICE_ADDR=cart-service:50053
      - DELIVERY_SERVICE_ADDR=delivery-service:50054
    networks:
      - microservices-network

  # Auth Service
  auth-service:
    build: ./services/auth
    container_name: auth-service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=auth_user
      - DB_PASSWORD=authpass
      - DB_NAME=auth_db
      - JWT_SECRET=secret-key
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network

  # Product Service
  product-service:
    build: ./services/product
    container_name: product-service
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=product_user
      - DB_PASSWORD=productpass
      - DB_NAME=product_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservices-network

  # Order Service
  cart-service:
    build: ./services/cart
    container_name: cart-service
    ports:
      - "50053:50053"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=cart_user
      - DB_PASSWORD=cartpass
      - DB_NAME=cart_db
      - AUTH_SERVICE_ADDR=auth-service:50051
    restart: on-failure
    depends_on:
      - mysql
     # - auth-service
    networks:
      - microservices-network

  # Delivery Service
  delivery-service:
    build: ./services/delivery
    container_name: delivery-service
    ports:
      - "50054:50054"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=delivery_user
      - DB_PASSWORD=deliverypass
      - DB_NAME=delivery_db
      - CART_SERVICE_ADDR=cart-service:50053
    restart: on-failure
    depends_on:
      - mysql
      - cart-service
    networks:
      - microservices-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network


volumes:
  mysql-data:

networks:
  microservices-network:
    driver: bridge