apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: microservices
data:
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_USER: "delivery_user"
    DB_PASSWORD: "deliverypass"
    DB_NAME: "delivery_db"