# services/cart/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: microservices
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c',
          'until nc -zv mysql.microservices.svc.cluster.local 3306; do echo "Waiting for MySQL"; sleep 2; done']
      containers:
      - name: cart-service
        image: jarviss77/cart-service:latest
        envFrom:
        - configMapRef:
            name: cart-config
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: microservices
spec:
  selector:
    app: cart-service
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053