apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: jarviss77/auth-service:latest
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051